org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

minecraft_version=1.21.11
neoforge_version=21.11.42
mod_id=flowtiers
mod_name=FlowTiers
mod_license=MIT
mod_version=1.8.6
mod_group_id=dev.fecl.flowtiers
mod_authors=Fecl
mod_description=Shows FlowPvP ranked stats in-game.
