pluginManagement {
	repositories {
		maven {
			name = 'NeoForged'
			url = 'https://maven.neoforged.net/releases'
		}
		gradlePluginPortal()
		mavenCentral()
	}
}

dependencyResolutionManagement {
	repositories {
		maven {
			name = 'NeoForged'
			url = 'https://maven.neoforged.net/releases'
		}
		mavenCentral()
	}
}

rootProject.name = 'flowtiers'
